### ISSUE TITLE
As a data shopper, I would like the links at the top of Overview to be clickable, so I can find out more about them

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/data.beeldengeluid.nl#111]
![image](https://github.com/beeldengeluid/data.beeldengeluid.nl/assets/38520885/f6e5b3c7-a0e0-4dfb-8189-acb9478b0baa)

These pieces of information appear as if they should be links - especially the rights statement - and invite to be clicked on to find out more, but they are not clickable. Would expect to go to the metadata when clicking on the number of records.

Tasks:
- [ ] Consider if it is feasible to make (some of) these links clickable
- [ ] If not, consider altering their appearance so it is clear that they are static information

Acceptance criteria:
- [ ] Either these pieces of information are clickable links, or it is clear that they are static pieces of information

**Comment by KleinRana** [comment]
Remove these pieces of information (not clickable buttons).


Merge tabs overview & metadata included in #81
