### ISSUE TITLE
Create a dashboard for the Amateurfilm collection

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/data.beeldengeluid.nl#171]
Tasks:
- [x] Merge Vega changes
- [x] Look at what the dashboard should contain - what is useful to show about this collection?
- [x] Create the dashboard 
- [x] Review with Dimitra and Valentina, adjust where necessary
- [x] Create an NL version
- [x] Update numbers

**Comment by mwigham** [comment]
Initial set from which Valentina and Dimtra can make a selection (or of course request new visualisations):
- Number of items over time
- Geographical location
- Series genre and programme genre (amateuropname excluded) 
- Subject term (amateuropnamen excluded)
- Corporation ( jaren ** excluded)
- Silent film
- Colour

**Comment by mwigham** [comment]
@DimitraAts could you and Valentina review this please? Take a look at the [preview](https://data-beeldengeluid-nl-git-171-amateur-dashboard-beeldengeluid.vercel.app/nl), go to the Datasets page, then choose Amateurfilm and click on the Dashboard tab. Please let me know which of these visualisations would be suitable for the purposes of giving people more insight into what the collection contains. Also let me know please if there are other visualisations you would like to have, or if you have any other comments. Thanks!

**Comment by DimitraAts** [comment]
@mwigham Valentine suggested to add the carrier format (dragerformaat), to show the division between 16mm, super8, 8mm, VHS etc. We shortly discussed adding the creator, but that seems to say not that much about the collection as a whole. Other than the carrier format, the visualization is quite extensive and complete, and gives a good insight of what the collection contains.

**Comment by mwigham** [comment]
@DimitraAts thanks, I'll add that visualisation and then close the issue.

**Comment by mwigham** [comment]
@DimitraAts This is unfortunately a bit of an awkward one, as the values you are interested in are split over two different fields. If we look at the carrier type, we get this top 10:


![Image](https://github.com/beeldengeluid/data.beeldengeluid.nl/assets/38520885/8a636a76-c898-4e9e-8215-d3458a77bbfd)

But this doesn't include 8 or 16mm. These are registered in the carrier format field (top 10):


![Image](https://github.com/beeldengeluid/data.beeldengeluid.nl/assets/38520885/1b409fce-04aa-424f-8506-d2bd4f51d1a3)

We could include both graphs. Or we could simply list the numbers for the selected types that you think people are interested in, from both fields. I wouldn't suggest creating a graph that combines both fields as that could be misleading.

**Comment by wmelder** [comment]
- [ ] @DimitraAts ask valentineabout the visualisation for the carrier format
- [ ] critical look at the metadata fields and missing ones

**Comment by DimitraAts** [comment]
@mwigham dit antwoord kreeg ik terug van Valentine en lijkt mij ook een goede suggestie, maar is dat werkbaar voor jou? 

“Ik denk dat je dan de filmformaten uit 'carrier format' moet halen en de dragerformaten / types uit 'carrier type'. En zonder dubbelingen te krijgen heb je denk ik het volgende nodig:

carrier type:
- video8
- hi8
- VHS
- Umatic
- DVD

carrier format
- 8 mm
- 16 mm
- 17,5 mm
- 35 mm
- 9,5 mm

Als dat niet lukt, dan zouden we carrier format helemaal uit moeten sluiten en bij 'carrier type' FILM toevoegen als type”

**Comment by mwigham** [comment]
Grafieken voor formaat en type zijn toegevoegd, ik sluit deze issue. Let op: de PR kan nog niet worden gemerged, lees de PR voor meer info.
